
name: ocr_mrz
description: "A new Flutter package uses ocr to get mrz"
version: 0.0.99

publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  camera_kit_plus: ^0.0.48
  http: ^1.6.0
  collection: ^1.19.1
  image: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/scanner_frame.png